= WildFly Monitor

image:https://travis-ci.org/rhq-project/wildfly-monitor.svg?branch=master["Build Status", link="https://travis-ci.org/rhq-project/wildfly-monitor"]

This is a module to be deployed into WildFlyAS and which then takes
measurements from the WildFly model and sends them to a https://github.com/rhq-project/wildfly-monitor/wiki/RHQ[RHQ-Metrics server] or https://github.com/rhq-project/wildfly-monitor/wiki/InfluxDB[InfluxDB]

== Prerequisites

=== Wildfly 8.1.0

Get and install Wildfly 8.1.0: http://download.jboss.org/wildfly/8.1.0.Final/wildfly-8.1.0.Final.zip

It's currently been tested against WF 8.1.0 and the default server configuration (standalone-monitor.xml) is configured for WF 8.
But apart from that there should be no reason to not use it on WF 9.

=== RHQ Metrics

https://github.com/rhq-project/rhq-metrics[RHQ Metrics] is not part of this module. It needs to be installed separately. Please consult the RHQ metrics documentation,
how to install the core metric components and the REST services onto Wildfly 8.


== Build & Install

Build the top level project:

----
$ mvn clean install
----

This will also create a wildfly-monitor-module.zip, that can be installed on Wildfly:

`unzip target/wildfly-monitor-module.zip -d $WILDFLY_HOME`

This will add an additional module that contains the monitor extension and subsystem:

`modules/system/layers/base/org/rhq/metrics/wildfly-monitor/`

== Package Contents

The following contents will be installed when you unpack the wildfly-monitor-module.zip:

....
modules/system/layers/base/org/rhq/metrics/wildfly-monitor/main/module.xml (1)
modules/system/layers/base/org/rhq/metrics/wildfly-monitor/main/*.jar (2)
standalone/configuration/standalone-monitor.xml (3)
domain/configuration/monitor-domain.xml (4)
domain/configuration/monitor-host.xml (5)`
....

. The module descriptor
. Required libraries to run the monitor on Wildfly
. An example configuration for standalone servers
. An example configuration for managed domains
. An example host configuration

## Server Configuration Profiles

The wildfly-monitor-module.zip server profiles for both standalone and domain mode that can be used to start a pre-configured Wildfly instance:

### Standalone Mode

`./bin/standalone.sh -c standalone-monitor.xml -b 127.0.0.1`

### Domain Mode

`./bin/domain.sh --domain-config=monitor-domain.xml --host-config=monitor-host.xml -b 127.0.0.1`


## Get In touch

The best way to reach out and discuss the monitor subsystem is the RHQ  mailing list and/or the Chat Room:

- Mailing List: https://lists.fedorahosted.org/mailman/listinfo/rhq-devel
- IRC: irc://freenode.org/#rhq

## License

- http://www.apache.org/licenses/LICENSE-2.0.html

## Resources
- https://docs.jboss.org/author/display/WFLY8/Documentation

